services:
  hyperf-skeleton:
    container_name: hyperf-skeleton
    image: hyperf-skeleton
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - DB_HOST=mysql
      - DB_DATABASE=hyperf
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      - mysql
      - mailhog
    networks:
      - hyperf-network

  mysql:
    image: mysql:8
    container_name: hyperf-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hyperf
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hyperf-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: hyperf-mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - hyperf-network

networks:
  hyperf-network:
    driver: bridge

volumes:
  mysql_data:
